// apps/web/vue/src/components/acp/AcpPlanView.vue
<!--
  HAP-1047: ACP Plan Display Component

  Renders the current execution plan from ACP session updates.
  Each plan entry shows its status (pending/in_progress/completed)
  with appropriate visual indicators.
-->
<script setup lang="ts">
import { useI18n } from 'vue-i18n';
import {
  IconList,
  IconCircleCheck,
  IconCircleFilled,
  IconCircle,
} from '@tabler/icons-vue';
import type { AcpPlanEntry, AcpPlanEntryStatus } from '@magic-agent/protocol';

const props = defineProps<{
  entries: AcpPlanEntry[];
}>();

const { t } = useI18n();

function statusIconClass(status: AcpPlanEntryStatus): string {
  switch (status) {
    case 'completed':
      return 'text-green-500';
    case 'in_progress':
      return 'text-primary';
    case 'pending':
    default:
      return 'text-muted-foreground';
  }
}
</script>

<template>
  <div v-if="props.entries.length > 0" class="rounded-xl bg-muted/50 p-3 my-1">
    <div class="mb-2 flex items-center gap-1.5">
      <IconList class="size-4 text-muted-foreground" />
      <span class="text-[13px] font-semibold text-muted-foreground">
        {{ t('acp.plan') }}
      </span>
    </div>
    <div
      v-for="(entry, index) in props.entries"
      :key="index"
      class="flex items-start gap-2 py-1"
    >
      <IconCircleCheck
        v-if="entry.status === 'completed'"
        class="mt-0.5 size-4 shrink-0"
        :class="statusIconClass(entry.status)"
      />
      <IconCircleFilled
        v-else-if="entry.status === 'in_progress'"
        class="mt-0.5 size-4 shrink-0"
        :class="statusIconClass(entry.status)"
      />
      <IconCircle
        v-else
        class="mt-0.5 size-4 shrink-0"
        :class="statusIconClass(entry.status)"
      />
      <span
        class="flex-1 text-sm leading-5"
        :class="{
          'text-muted-foreground line-through': entry.status === 'completed',
          'text-foreground': entry.status !== 'completed',
        }"
      >
        {{ entry.content }}
      </span>
    </div>
  </div>
</template>

// apps/web/react/sources/components/acp/AcpPlanView.tsx
/**
 * HAP-1036: ACP Plan Display Component
 *
 * Renders the current execution plan from ACP session updates.
 * Each plan entry shows its status (pending/in_progress/completed)
 * with appropriate visual indicators.
 */

import * as React from 'react';
import { Text, View } from 'react-native';
import { StyleSheet, useUnistyles } from 'react-native-unistyles';
import Ionicons from '@expo/vector-icons/Ionicons';
import type { AcpPlanEntry, AcpPlanEntryStatus } from '@magic-agent/protocol';
import { t } from '@/text';

interface AcpPlanViewProps {
    entries: AcpPlanEntry[];
}

function getStatusIcon(status: AcpPlanEntryStatus, theme: any) {
    switch (status) {
        case 'completed':
            return <Ionicons name="checkmark-circle" size={16} color={theme.colors.success ?? '#34C759'} />;
        case 'in_progress':
            return <Ionicons name="ellipse" size={16} color={theme.colors.primary} />;
        case 'pending':
        default:
            return <Ionicons name="ellipse-outline" size={16} color={theme.colors.textSecondary} />;
    }
}

export const AcpPlanView = React.memo<AcpPlanViewProps>(({ entries }) => {
    const { theme } = useUnistyles();

    if (entries.length === 0) return null;

    return (
        <View style={styles.container}>
            <View style={styles.header}>
                <Ionicons name="list-outline" size={16} style={styles.headerIcon} />
                <Text style={styles.headerText}>{t('acp.plan')}</Text>
            </View>
            {entries.map((entry, index) => (
                <View key={index} style={styles.entry}>
                    <View style={styles.statusIcon}>
                        {getStatusIcon(entry.status, theme)}
                    </View>
                    <Text
                        style={[
                            styles.entryText,
                            entry.status === 'completed' && styles.entryTextCompleted,
                        ]}
                        numberOfLines={2}
                    >
                        {entry.content}
                    </Text>
                </View>
            ))}
        </View>
    );
});

const styles = StyleSheet.create((theme) => ({
    container: {
        backgroundColor: theme.colors.backgroundSecondary,
        borderRadius: 12,
        padding: 12,
        marginVertical: 4,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    headerIcon: {
        color: theme.colors.textSecondary,
        marginRight: 6,
    },
    headerText: {
        fontSize: 13,
        fontWeight: '600',
        color: theme.colors.textSecondary,
    },
    entry: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingVertical: 4,
    },
    statusIcon: {
        marginRight: 8,
        marginTop: 1,
    },
    entryText: {
        flex: 1,
        fontSize: 14,
        color: theme.colors.typography,
        lineHeight: 20,
    },
    entryTextCompleted: {
        color: theme.colors.textSecondary,
        textDecorationLine: 'line-through',
    },
}));
