// apps/web/vue/src/components/acp/AcpStreamingText.vue
<!--
  HAP-1047: ACP Streaming Text Component

  Renders streaming agent message text using the existing MarkdownView
  component. Wraps the streaming text with proper layout handling.
-->
<script setup lang="ts">
import { MarkdownView } from '@/components/app';

const props = defineProps<{
  text: string;
}>();
</script>

<template>
  <div v-if="props.text" class="my-1">
    <MarkdownView :markdown="props.text" />
  </div>
</template>

// apps/web/react/sources/components/acp/AcpStreamingText.tsx
/**
 * HAP-1036: ACP Streaming Text Component
 *
 * Renders streaming agent message text using the existing MarkdownView
 * component. Wraps the streaming text with proper layout handling.
 */

import * as React from 'react';
import { View } from 'react-native';
import { StyleSheet } from 'react-native-unistyles';
import { MarkdownView } from '@/components/markdown/MarkdownView';

interface AcpStreamingTextProps {
    text: string;
}

export const AcpStreamingText = React.memo<AcpStreamingTextProps>(({ text }) => {
    if (!text) return null;

    return (
        <View style={styles.container}>
            <MarkdownView markdown={text} />
        </View>
    );
});

const styles = StyleSheet.create(() => ({
    container: {
        marginVertical: 4,
    },
}));
