// apps/web/react/sources/components/acp/AcpContentBlockRenderer.tsx
/**
 * HAP-1042: ACP Content Block Renderer (Dispatcher)
 *
 * Selects and renders the appropriate component for each ACP content
 * block type. Handles both direct content blocks (text, image,
 * resource_link, resource) and tool call content blocks (content, diff,
 * terminal).
 *
 * Unknown content types are rendered with a graceful fallback showing
 * raw text representation.
 */

import * as React from 'react';
import { Text, View } from 'react-native';
import { StyleSheet } from 'react-native-unistyles';
import type {
    AcpContentBlock,
    AcpToolCallContent,
} from '@magic-agent/protocol';
import { AcpStreamingText } from './AcpStreamingText';
import { AcpImageBlock } from './AcpImageBlock';
import { AcpResourceLinkBlock, AcpEmbeddedResourceBlock } from './AcpResourceBlock';
import { AcpDiffView } from './AcpDiffView';
import { AcpTerminalOutput } from './AcpTerminalOutput';
import { t } from '@/text';

// ─── Content Block Renderer ─────────────────────────────────────────────────

interface AcpContentBlockRendererProps {
    content: AcpContentBlock;
}

/**
 * Dispatches rendering of an ACP content block to the appropriate
 * specialized component based on the `type` discriminator.
 */
export const AcpContentBlockRenderer = React.memo<AcpContentBlockRendererProps>(({ content }) => {
    switch (content.type) {
        case 'text':
            return <AcpStreamingText text={content.text} />;

        case 'image':
            return <AcpImageBlock content={content} />;

        case 'resource_link':
            return <AcpResourceLinkBlock content={content} />;

        case 'resource':
            return <AcpEmbeddedResourceBlock content={content} />;

        case 'audio':
            // Audio is out of scope (HAP-1042)
            return (
                <View style={styles.fallbackContainer}>
                    <Text style={styles.fallbackText}>
                        {t('acp.content.audioUnsupported')}
                    </Text>
                </View>
            );

        default:
            return (
                <View style={styles.fallbackContainer}>
                    <Text style={styles.fallbackText}>
                        {t('acp.content.unknownType', { type: (content as any).type ?? 'unknown' })}
                    </Text>
                </View>
            );
    }
});

// ─── Tool Call Content Renderer ─────────────────────────────────────────────

interface AcpToolCallContentRendererProps {
    content: AcpToolCallContent;
}

/**
 * Dispatches rendering of an ACP tool call content block to the appropriate
 * specialized component based on the `type` discriminator.
 */
export const AcpToolCallContentRenderer = React.memo<AcpToolCallContentRendererProps>(({ content }) => {
    switch (content.type) {
        case 'content':
            return <AcpContentBlockRenderer content={content.content} />;

        case 'diff':
            return <AcpDiffView content={content} />;

        case 'terminal':
            return <AcpTerminalOutput terminalId={content.terminalId} />;

        default:
            return (
                <View style={styles.fallbackContainer}>
                    <Text style={styles.fallbackText}>
                        {t('acp.content.unknownType', { type: (content as any).type ?? 'unknown' })}
                    </Text>
                </View>
            );
    }
});

// ─── Styles ─────────────────────────────────────────────────────────────────

const styles = StyleSheet.create((theme) => ({
    fallbackContainer: {
        backgroundColor: theme.colors.backgroundSecondary,
        borderRadius: 10,
        padding: 12,
        marginVertical: 2,
    },
    fallbackText: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        fontStyle: 'italic',
    },
}));

// apps/web/vue/src/components/acp/AcpContentBlockRenderer.vue
<!--
  HAP-1047: ACP Content Block Renderer (Dispatcher)

  Selects and renders the appropriate component for each ACP content
  block type. Handles text, image, resource_link, resource types.
  Unknown content types are rendered with a graceful fallback.
-->
<script setup lang="ts">
import { useI18n } from 'vue-i18n';
import type { AcpContentBlock } from '@magic-agent/protocol';
import AcpStreamingText from './AcpStreamingText.vue';

const props = defineProps<{
  content: AcpContentBlock;
}>();

const { t } = useI18n();
</script>

<template>
  <AcpStreamingText v-if="props.content.type === 'text'" :text="props.content.text" />

  <div
    v-else-if="props.content.type === 'image'"
    class="my-1 overflow-hidden rounded-lg"
  >
    <img
      :src="`data:${props.content.mimeType};base64,${props.content.data}`"
      :alt="t('acp.content.image')"
      class="max-h-80 max-w-full object-contain"
    />
  </div>

  <div
    v-else-if="props.content.type === 'resource_link'"
    class="my-0.5 rounded-[10px] bg-muted/50 p-2.5"
  >
    <p class="text-sm font-medium text-foreground">
      {{ props.content.name }}
    </p>
    <p v-if="props.content.description" class="mt-0.5 text-xs text-muted-foreground">
      {{ props.content.description }}
    </p>
    <p class="mt-0.5 truncate font-mono text-xs text-muted-foreground">
      {{ props.content.uri }}
    </p>
  </div>

  <div
    v-else-if="props.content.type === 'resource'"
    class="my-0.5 rounded-[10px] bg-muted/50 p-2.5"
  >
    <p class="truncate font-mono text-xs text-muted-foreground">
      {{ props.content.resource.uri }}
    </p>
    <p v-if="'text' in props.content.resource" class="mt-1 text-sm text-foreground whitespace-pre-wrap">
      {{ props.content.resource.text }}
    </p>
  </div>

  <div v-else-if="props.content.type === 'audio'" class="my-0.5 rounded-[10px] bg-muted/50 p-3">
    <p class="text-[13px] italic text-muted-foreground">
      {{ t('acp.content.audioUnsupported') }}
    </p>
  </div>

  <div v-else class="my-0.5 rounded-[10px] bg-muted/50 p-3">
    <p class="text-[13px] italic text-muted-foreground">
      {{ t('acp.content.unknownType', { type: (props.content as any).type ?? 'unknown' }) }}
    </p>
  </div>
</template>
