// apps/web/react/sources/components/acp/AcpSessionBrowser.tsx
/**
 * HAP-1044: ACP Session Browser Component
 *
 * Displays a list of available ACP sessions with load, resume, and fork actions.
 * Actions are gated by agent capabilities. The active session is visually distinguished.
 * Supports pull-to-refresh and shows an empty state when no sessions are available.
 */

import * as React from 'react';
import { Text, View, FlatList, Pressable, ActivityIndicator, RefreshControl } from 'react-native';
import { StyleSheet, useUnistyles } from 'react-native-unistyles';
import Ionicons from '@expo/vector-icons/Ionicons';
import { t } from '@/text';
import { Modal } from '@/modal';
import type { AcpSessionBrowserCapabilities, AcpBrowserSession } from '@/sync/acpTypes';

interface AcpSessionBrowserProps {
    sessions: AcpBrowserSession[];
    capabilities: AcpSessionBrowserCapabilities;
    activeSessionId: string | null;
    onRefresh: () => void;
    onLoad: (sessionId: string) => void;
    onResume: (sessionId: string) => void;
    onFork: (sessionId: string) => void;
    refreshing: boolean;
}

function formatSessionDate(dateStr: string | null): string {
    if (!dateStr) return '';
    try {
        const date = new Date(dateStr);
        const now = new Date();
        const diffMs = now.getTime() - date.getTime();
        const diffMins = Math.floor(diffMs / 60000);
        if (diffMins < 1) return t('time.justNow');
        if (diffMins < 60) return t('time.minutesAgo', { count: diffMins });
        const diffHours = Math.floor(diffMins / 60);
        if (diffHours < 24) return t('time.hoursAgo', { count: diffHours });
        const diffDays = Math.floor(diffHours / 24);
        return t('time.daysAgo', { count: diffDays });
    } catch {
        return '';
    }
}

/**
 * Confirm before switching away from the active session.
 * Returns true if user confirms or there's no active session conflict.
 */
async function confirmSessionSwitch(activeSessionId: string | null, targetSessionId: string): Promise<boolean> {
    if (!activeSessionId || activeSessionId === targetSessionId) return true;
    return Modal.confirm(
        t('acp.sessionBrowser.switchSessionTitle'),
        t('acp.sessionBrowser.switchSessionMessage'),
        {
            confirmText: t('common.continue'),
            cancelText: t('common.cancel'),
        }
    );
}

const EmptyState = React.memo(() => {
    return (
        <View style={styles.emptyContainer}>
            <Ionicons name="albums-outline" size={48} style={styles.emptyIcon} />
            <Text style={styles.emptyTitle}>{t('acp.sessionBrowser.emptyTitle')}</Text>
            <Text style={styles.emptyDescription}>{t('acp.sessionBrowser.emptyDescription')}</Text>
        </View>
    );
});

interface SessionItemProps {
    session: AcpBrowserSession;
    capabilities: AcpSessionBrowserCapabilities;
    activeSessionId: string | null;
    onLoad: (sessionId: string) => void;
    onResume: (sessionId: string) => void;
    onFork: (sessionId: string) => void;
}

const SessionItem = React.memo<SessionItemProps>(({
    session,
    capabilities,
    activeSessionId,
    onLoad,
    onResume,
    onFork,
}) => {
    const { theme } = useUnistyles();

    const handleLoad = React.useCallback(async () => {
        if (await confirmSessionSwitch(activeSessionId, session.sessionId)) {
            onLoad(session.sessionId);
        }
    }, [activeSessionId, session.sessionId, onLoad]);

    const handleResume = React.useCallback(async () => {
        if (await confirmSessionSwitch(activeSessionId, session.sessionId)) {
            onResume(session.sessionId);
        }
    }, [activeSessionId, session.sessionId, onResume]);

    const handleFork = React.useCallback(async () => {
        onFork(session.sessionId);
    }, [session.sessionId, onFork]);

    const hasActions = capabilities.canLoadSession || capabilities.canResumeSession || capabilities.canForkSession;

    return (
        <View style={[styles.sessionItem, session.isActive && styles.sessionItemActive]}>
            <View style={styles.sessionHeader}>
                <View style={styles.sessionTitleRow}>
                    <Text style={styles.sessionTitle} numberOfLines={1}>
                        {session.title}
                    </Text>
                    {session.isActive && (
                        <View style={styles.activeBadge}>
                            <View style={[styles.activeDot, { backgroundColor: theme.colors.success ?? '#34C759' }]} />
                            <Text style={[styles.activeBadgeText, { color: theme.colors.success ?? '#34C759' }]}>
                                {t('acp.sessionBrowser.active')}
                            </Text>
                        </View>
                    )}
                </View>
                <Text style={styles.sessionCwd} numberOfLines={1}>{session.cwd}</Text>
                {session.updatedAt && (
                    <Text style={styles.sessionDate}>{formatSessionDate(session.updatedAt)}</Text>
                )}
            </View>
            {hasActions && !session.isActive && (
                <View style={styles.actionRow}>
                    {capabilities.canLoadSession && (
                        <Pressable style={styles.actionButton} onPress={handleLoad}>
                            <Ionicons name="open-outline" size={14} style={styles.actionIcon} />
                            <Text style={styles.actionText}>{t('acp.sessionBrowser.load')}</Text>
                        </Pressable>
                    )}
                    {capabilities.canResumeSession && (
                        <Pressable style={styles.actionButton} onPress={handleResume}>
                            <Ionicons name="play-outline" size={14} style={styles.actionIcon} />
                            <Text style={styles.actionText}>{t('acp.sessionBrowser.resume')}</Text>
                        </Pressable>
                    )}
                    {capabilities.canForkSession && (
                        <Pressable style={styles.actionButton} onPress={handleFork}>
                            <Ionicons name="git-branch-outline" size={14} style={styles.actionIcon} />
                            <Text style={styles.actionText}>{t('acp.sessionBrowser.fork')}</Text>
                        </Pressable>
                    )}
                </View>
            )}
        </View>
    );
});

const keyExtractor = (item: AcpBrowserSession) => item.sessionId;

export const AcpSessionBrowser = React.memo<AcpSessionBrowserProps>(({
    sessions,
    capabilities,
    activeSessionId,
    onRefresh,
    onLoad,
    onResume,
    onFork,
    refreshing,
}) => {
    const { theme } = useUnistyles();

    const renderItem = React.useCallback(({ item }: { item: AcpBrowserSession }) => (
        <SessionItem
            session={item}
            capabilities={capabilities}
            activeSessionId={activeSessionId}
            onLoad={onLoad}
            onResume={onResume}
            onFork={onFork}
        />
    ), [capabilities, activeSessionId, onLoad, onResume, onFork]);

    return (
        <View style={styles.container}>
            <Text style={styles.headerTitle}>{t('acp.sessionBrowser.title')}</Text>
            <FlatList
                data={sessions}
                keyExtractor={keyExtractor}
                renderItem={renderItem}
                contentContainerStyle={sessions.length === 0 ? styles.emptyListContent : styles.listContent}
                ListEmptyComponent={refreshing ? (
                    <View style={styles.loadingContainer}>
                        <ActivityIndicator size="small" color={theme.colors.primary} />
                    </View>
                ) : (
                    <EmptyState />
                )}
                refreshControl={
                    <RefreshControl
                        refreshing={refreshing}
                        onRefresh={onRefresh}
                        tintColor={theme.colors.primary}
                    />
                }
            />
        </View>
    );
});

const styles = StyleSheet.create((theme) => ({
    container: {
        flex: 1,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: theme.colors.typography,
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 12,
    },
    listContent: {
        paddingHorizontal: 16,
        paddingBottom: 16,
    },
    emptyListContent: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingContainer: {
        paddingVertical: 40,
        alignItems: 'center',
    },
    emptyContainer: {
        alignItems: 'center',
        paddingHorizontal: 32,
    },
    emptyIcon: {
        color: theme.colors.textSecondary,
        marginBottom: 12,
    },
    emptyTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.typography,
        marginBottom: 4,
    },
    emptyDescription: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        textAlign: 'center',
    },
    sessionItem: {
        backgroundColor: theme.colors.backgroundSecondary,
        borderRadius: 12,
        padding: 14,
        marginBottom: 8,
    },
    sessionItemActive: {
        borderWidth: 1.5,
        borderColor: theme.colors.primary,
    },
    sessionHeader: {
        gap: 2,
    },
    sessionTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    sessionTitle: {
        flex: 1,
        fontSize: 15,
        fontWeight: '600',
        color: theme.colors.typography,
        marginRight: 8,
    },
    activeBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    activeDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
    },
    activeBadgeText: {
        fontSize: 11,
        fontWeight: '600',
    },
    sessionCwd: {
        fontSize: 12,
        color: theme.colors.textSecondary,
        fontFamily: 'monospace',
    },
    sessionDate: {
        fontSize: 11,
        color: theme.colors.textSecondary,
        marginTop: 2,
    },
    actionRow: {
        flexDirection: 'row',
        gap: 8,
        marginTop: 10,
        paddingTop: 10,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: theme.colors.border,
    },
    actionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.background,
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 6,
        gap: 4,
    },
    actionIcon: {
        color: theme.colors.primary,
    },
    actionText: {
        fontSize: 13,
        fontWeight: '500',
        color: theme.colors.primary,
    },
}));

// apps/web/vue/src/components/acp/AcpSessionBrowser.vue
<!--
  HAP-1048: ACP Session Browser Component

  Panel listing available ACP sessions with load, resume, and fork actions.
  Actions are gated by agent capabilities. The active session is visually
  distinguished. Supports loading/empty states and confirmation before
  switching away from an active session.
-->
<script setup lang="ts">
import { ref, computed } from "vue";
import { useI18n } from "vue-i18n";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import type { AcpBrowserSession, AcpSessionBrowserCapabilities } from "@/stores/acpTypes";

const props = defineProps<{
  sessions: AcpBrowserSession[];
  capabilities: AcpSessionBrowserCapabilities;
  activeSessionId: string | null;
  loading: boolean;
}>();

const emit = defineEmits<{
  refresh: [];
  load: [sessionId: string];
  resume: [sessionId: string];
  fork: [sessionId: string];
}>();

const { t } = useI18n();

// ─── Confirmation Dialog ────────────────────────────────────────────────────

const confirmOpen = ref(false);
const confirmAction = ref<{ type: "load" | "resume"; sessionId: string } | null>(null);

function requestAction(type: "load" | "resume", sessionId: string) {
  if (props.activeSessionId && props.activeSessionId !== sessionId) {
    confirmAction.value = { type, sessionId };
    confirmOpen.value = true;
  } else {
    performAction(type, sessionId);
  }
}

function performAction(type: "load" | "resume", sessionId: string) {
  if (type === "load") emit("load", sessionId);
  else emit("resume", sessionId);
}

function handleConfirm() {
  if (confirmAction.value) {
    performAction(confirmAction.value.type, confirmAction.value.sessionId);
  }
  confirmOpen.value = false;
  confirmAction.value = null;
}

function handleCancel() {
  confirmOpen.value = false;
  confirmAction.value = null;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function formatSessionDate(dateStr: string | null): string {
  if (!dateStr) return "";
  try {
    const date = new Date(dateStr);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    if (diffMins < 1) return t("acp.sessionBrowser.justNow");
    if (diffMins < 60) return t("acp.sessionBrowser.minutesAgo", { count: diffMins });
    const diffHours = Math.floor(diffMins / 60);
    if (diffHours < 24) return t("acp.sessionBrowser.hoursAgo", { count: diffHours });
    const diffDays = Math.floor(diffHours / 24);
    return t("acp.sessionBrowser.daysAgo", { count: diffDays });
  } catch {
    return "";
  }
}

const hasActions = computed(
  () =>
    props.capabilities.canLoadSession ||
    props.capabilities.canResumeSession ||
    props.capabilities.canForkSession,
);
</script>

<template>
  <div class="flex flex-col">
    <!-- Header -->
    <div class="flex items-center justify-between px-4 pt-4 pb-3">
      <h3 class="text-lg font-bold">{{ t("acp.sessionBrowser.title") }}</h3>
      <Button variant="ghost" size="sm" :disabled="loading" @click="emit('refresh')">
        <svg
          class="h-4 w-4"
          :class="loading ? 'animate-spin' : ''"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path d="M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" />
          <path d="M3 3v5h5" />
          <path d="M3 12a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16" />
          <path d="M16 16h5v5" />
        </svg>
      </Button>
    </div>

    <!-- Loading state -->
    <div v-if="loading && sessions.length === 0" class="flex items-center justify-center py-10">
      <svg
        class="h-5 w-5 animate-spin text-primary"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <path d="M21 12a9 9 0 1 1-6.219-8.56" />
      </svg>
    </div>

    <!-- Empty state -->
    <div
      v-else-if="sessions.length === 0"
      class="flex flex-col items-center justify-center py-10 px-8 text-center"
    >
      <svg
        class="h-12 w-12 text-muted-foreground/50 mb-3"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <rect x="2" y="4" width="20" height="16" rx="2" />
        <path d="M2 8h20" />
        <path d="M2 12h20" />
      </svg>
      <p class="font-medium">{{ t("acp.sessionBrowser.emptyTitle") }}</p>
      <p class="text-sm text-muted-foreground mt-1">
        {{ t("acp.sessionBrowser.emptyDescription") }}
      </p>
    </div>

    <!-- Session list -->
    <ScrollArea v-else class="px-4 pb-4">
      <div class="space-y-2">
        <div
          v-for="session in sessions"
          :key="session.sessionId"
          class="rounded-xl border bg-card p-3.5 transition-colors"
          :class="session.isActive ? 'border-primary' : 'border-border'"
        >
          <div class="space-y-0.5">
            <div class="flex items-center justify-between">
              <p class="font-medium truncate mr-2">{{ session.title }}</p>
              <Badge
                v-if="session.isActive"
                variant="default"
                class="shrink-0 text-[10px] px-1.5 py-0"
              >
                <span class="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-current" />
                {{ t("acp.sessionBrowser.active") }}
              </Badge>
            </div>
            <p class="text-xs text-muted-foreground font-mono truncate">
              {{ session.cwd }}
            </p>
            <p v-if="session.updatedAt" class="text-[11px] text-muted-foreground">
              {{ formatSessionDate(session.updatedAt) }}
            </p>
          </div>

          <!-- Actions -->
          <div v-if="hasActions && !session.isActive" class="flex gap-2 mt-2.5 pt-2.5 border-t">
            <Button
              v-if="capabilities.canLoadSession"
              variant="ghost"
              size="sm"
              class="h-7 text-xs"
              @click="requestAction('load', session.sessionId)"
            >
              <svg
                class="h-3 w-3 mr-1"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
                <polyline points="15 3 21 3 21 9" />
                <line x1="10" y1="14" x2="21" y2="3" />
              </svg>
              {{ t("acp.sessionBrowser.load") }}
            </Button>
            <Button
              v-if="capabilities.canResumeSession"
              variant="ghost"
              size="sm"
              class="h-7 text-xs"
              @click="requestAction('resume', session.sessionId)"
            >
              <svg
                class="h-3 w-3 mr-1"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <polygon points="5 3 19 12 5 21 5 3" />
              </svg>
              {{ t("acp.sessionBrowser.resume") }}
            </Button>
            <Button
              v-if="capabilities.canForkSession"
              variant="ghost"
              size="sm"
              class="h-7 text-xs"
              @click="emit('fork', session.sessionId)"
            >
              <svg
                class="h-3 w-3 mr-1"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <circle cx="12" cy="18" r="3" />
                <circle cx="6" cy="6" r="3" />
                <circle cx="18" cy="6" r="3" />
                <path d="M18 9v2c0 .6-.4 1-1 1H7c-.6 0-1-.4-1-1V9" />
                <path d="M12 12v3" />
              </svg>
              {{ t("acp.sessionBrowser.fork") }}
            </Button>
          </div>
        </div>
      </div>
    </ScrollArea>

    <!-- Confirmation dialog -->
    <AlertDialog :open="confirmOpen">
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>{{ t("acp.sessionBrowser.switchSessionTitle") }}</AlertDialogTitle>
          <AlertDialogDescription>
            {{ t("acp.sessionBrowser.switchSessionMessage") }}
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel @click="handleCancel">
            {{ t("common.cancel") }}
          </AlertDialogCancel>
          <AlertDialogAction @click="handleConfirm">
            {{ t("common.continue") }}
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  </div>
</template>
